import Link from 'next/link';

export const metadata = { title: 'Methodology — The Big One Loss Estimator' };

export default function Methodology() {
  return (
    <main className="page-main">
      <article className="prose">
        <Link href="/" className="back-link">
          ← back to the map
        </Link>
        <h1>Methodology</h1>
        <p>
          This page describes the v0.3 modeling chain end to end. The source of
          truth is the open repository; everything below is reproducible from
          the committed pipeline.
        </p>

        <h2>What this is (and is not)</h2>
        <p>
          Scenario-based loss estimation with quantified uncertainty — the same
          framing used by USGS PAGER and GEM OpenQuake — not a prediction of
          when an earthquake will occur or a precise forecast of damages. Every
          figure is a P10/P50/P90 range, and the model is never tuned to match
          any published benchmark.
        </p>

        <h2>Scenario magnitude range</h2>
        <p>
          Scenarios span M6.0–M7.2, anchored on the PHIVOLCS maximum-credible
          magnitude of 7.2 for the ~100-km West Valley Fault, plus an M7.5
          stress test reflecting paleoseismic upper-bound estimates — treating
          maximum magnitude itself as an epistemically uncertain parameter.
        </p>

        <h2>Ground shaking</h2>
        <p>
          For each scenario magnitude, shaking intensity per LGU is computed
          with the Allen, Wald &amp; Worden (2012) intensity prediction
          equation for active crustal regions (rupture-distance version,
          coefficients cross-checked against the GEM OpenQuake implementation),
          using the distance from each LGU centroid to the West Valley Fault
          surface trace. The equation&apos;s published, distance-dependent
          sigma is carried forward into the Monte Carlo rather than discarded.
        </p>

        <h2>Exposure</h2>
        <p>
          Thirty-five LGUs: all seventeen NCR cities and the municipality of
          Pateros, plus eighteen fault-corridor LGUs in Bulacan, Rizal, Laguna,
          and Cavite. Exposure value per LGU is annual economic output scaled
          by a capital-output ratio. Where the PSA publishes city-level GDP
          (eight NCR cities covering roughly 85% of the regional economy,
          2024 Provincial Product Accounts), those figures are used, adjusted
          from constant 2018 prices to nominal with a documented deflator;
          the remaining LGUs use population times regional per-capita output.
          Every scenario file flags this mixed weighting.
        </p>

        <h2>Loss model</h2>
        <p>
          Losses are generated by a mechanistic exposure × fragility chain
          inside a nested Monte Carlo (60 epistemic × 60 aleatoric draws).
          Aleatoric uncertainty samples the intensity-prediction sigma with
          partial spatial correlation across LGUs (a common event-wide term,
          ρ = 0.5). Epistemic uncertainty samples the fragility curve and
          capital-output ratio — and as of v0.3 those parameters are
          <em> learned, not elicited</em> (next section). Losses use a
          logistic mean-damage-ratio curve in intensity; common random numbers
          across magnitudes keep the loss–magnitude curve monotone.
        </p>

        <h2>The learned component (where the machine learning lives)</h2>
        <p>
          The fragility parameters and capital-output ratio are calibrated by
          likelihood-free (ABC rejection) inference against the 1990 Mw 7.7
          Luzon earthquake: 200,000 prior draws are pushed through the same
          mechanistic forward model, and draws whose predicted total falls
          within an explicit interval-censoring window of the reported US$370M
          loss are retained as the posterior (~77,000 samples). This is
          physics-informed learning in the precise sense that the mechanistic
          structure (attenuation physics, exposure accounting, fragility form)
          constrains the hypothesis space while data updates the parameters.
          Separately, gradient-boosted quantile models trained on ~514 global
          historical events (NOAA NCEI, EM-DAT) are retained as an event-level
          cross-check in every scenario file: being exposure-blind, they
          underestimate the Metro Manila scenario by roughly two orders of
          magnitude — the empirical demonstration of why the hybrid is needed.
        </p>

        <h2>Validation: calibrate on 1990, hold out 2013</h2>
        <p>
          Because the West Valley Fault scenario has no observed precedent, the
          chain is validated on real Philippine earthquakes with a strict
          split: the 1990 Luzon event is used for calibration only, and the
          2013 Mw 7.2 Bohol earthquake is held out entirely. Out of sample, the
          hazard component reproduces Bohol&apos;s observed PEIS VIII
          epicentral / PEIS VII regional pattern within published sigma, and
          the calibrated loss chain predicts a P10–P90 of roughly US$45M–600M
          against the ₱2.257B (~US$52M) infrastructure-only monetized floor
          (NDRRMC) — consistent, given that 73,002 damaged houses were counted
          in units rather than pesos. As sanity anchors, the M7.2 national P50
          (~US$44B) sits at roughly 0.9× the World Bank&apos;s ~US$48B
          estimate and within the same order as the PHIVOLCS 2013 ₱2.4T
          building-damage figure; the successive versions moved from 0.01× to
          0.92× of the anchor purely through data and calibration improvements,
          never through tuning.
        </p>

        <h2>Uncertainty decomposition</h2>
        <p>
          The law of total variance over the nested Monte Carlo splits
          national-loss uncertainty into roughly two-thirds aleatoric
          (ground-motion randomness) and one-third epistemic (calibrated
          fragility and capital-ratio posterior) at M7.2 — reported live on
          the map for every scenario.
        </p>

        <h2>Sensitivity: which assumptions do the work?</h2>
        <p>
          A one-at-a-time tornado at the M7.2 anchor showed the fragility
          midpoint dominating (P50 −33% to +43% per prior standard deviation),
          followed by the maximum damage ratio and capital-output ratio, with
          exposure passing through linearly and spatial correlation moving
          interval width far more than the median — consistent with theory.
          That finding is what motivated the v0.3 calibration: the dominant
          assumption is now data-informed rather than elicited.
        </p>

        <h2>Open research questions (statuses)</h2>
        <p>
          (1)&nbsp;Aleatoric/epistemic separation — addressed in v0.3 via the
          calibrated posterior, with caveats: one calibration event, and the
          interval-censoring window is itself an assumption.
          (2)&nbsp;Validation under covariate shift — one held-out Philippine
          event (Bohol) passes; further candidates (2022 Abra, 2019 Mindanao)
          would strengthen the claim. (3)&nbsp;Ground truth is interval-censored
          — official totals undercount housing; handled explicitly but crudely.
          (4)&nbsp;Physics–data spectrum — addressed: mechanistic form with
          learned parameters. (5)&nbsp;Maximum magnitude — still scenarios plus
          a stress test rather than a distribution over Mmax.
          (6)&nbsp;Spatial resolution — held at LGU level; finer output without
          finer exposure would be false precision. Full write-ups in
          OPEN_QUESTIONS.md in the repository.
        </p>

        <h2>Sources and benchmarks</h2>
        <p>
          Intensity model: Allen, Wald &amp; Worden (2012), J. Seismology 16,
          coefficients cross-checked against GEM OpenQuake. Historical losses:
          NOAA NCEI Significant Earthquake Database (public domain) and EM-DAT
          (CRED, research license). Calibration event: 1990 Luzon (NOAA/NDCC:
          2,412 deaths, ~US$369.6M). Validation event: 2013 Bohol (NDRRMC
          SitRep 35: ₱2.257B infrastructure, 73,002 houses damaged).
          Benchmarks: PHIVOLCS maximum-credible M7.2 and the 2013
          PHIVOLCS-Australia ₱2.4T building-damage estimate; World Bank
          ~US$48B. Exposure: PSA 2024 Provincial Product Accounts (city GDP)
          and 2020 Census population. Comparables: Toyoda (2008) for Kobe;
          Haiti 2010 PDNA. Boundaries: PSGC 2023 via
          faeldon/philippines-json-maps.
        </p>

        <h2>Key limitations</h2>
        <p>
          Fragility is calibrated on a single event with a coarse
          interval-censoring window; historical loss databases carry
          survivorship and reporting bias; only direct losses are modeled (no
          business interruption or supply-chain effects); LGU-centroid
          distances ignore intra-city variation (most material for large
          corridor municipalities like Antipolo and Rodriguez); no
          liquefaction, site amplification, or fire-following modeling; the
          fault trace is the authoritative GEM WVF trace (Styron &amp; Pagani
          2020, CC-BY-SA) &mdash; wiring it in v0.3 lifted the national M7.2
          P50 by +2.7% ($44.2B &rarr; $45.4B, ratio 0.95&times; the $48B
          MMEIRS/World Bank anchor), with mean per-LGU MMI shifts &le;&plusmn;0.1
          but per-LGU maxima of ~0.45 MMI / &plusmn;7.5 km Rrup; and annual
          output scaled by a capital ratio remains an imperfect proxy for
          building stock value.
        </p>
      </article>
    </main>
  );
}
