#!/usr/bin/env python3
"""Render LEDGER.md from log.md (narrative) + status.csv (data).
Run after editing either file:  python3 render_ledger.py"""
import csv, os
from collections import defaultdict, OrderedDict

HERE = os.path.dirname(os.path.abspath(__file__))
STATUS = os.path.join(HERE, "status.csv")
LOG = os.path.join(HERE, "log.md")
OUT = os.path.join(os.path.dirname(HERE), "LEDGER.md")

# 8 RA 10121 obligations (id -> short label, citation)
OBLIG = OrderedDict([
    ("OB1", ("LDRRMO established",                         "RA10121 §12(a)")),
    ("OB2", ("LDRRMP formulated, tested & updated",        "§11(b)(1); §12(c)(6)")),
    ("OB3", ("Ordinance creating DRRMO (staff+budget)",    "IRR Rule 6 §6")),
    ("OB4", ("Hazard maps & plans PUBLICLY displayed",     "IRR Rule 6 §7; §12(c)(10)")),
    ("OB5", ("Local risk assessment / hazard ID",          "§12(c)(2,3,9)")),
    ("OB6", ("Regular drills conducted",                   "IRR Rule 6 §7; §12(c)(4)")),
    ("OB7", ("LDRRM Fund incl. 30% QRF programmed",        "§21")),
    ("OB8", ("DRR mainstreamed into CDP/CLUP",             "§11(b)(2)")),
])
LGUS = ["Makati", "Marikina", "Pasig", "Quezon City", "Pateros"]
GLYPH = {"present": "✓", "partial": "◐", "to-collect": "·", "absent": "✗"}
# real compliance lapses (surfaced in matrix flags + register); 'unverified' is
# just a collection gap already conveyed by the to-collect status, so it's excluded
REAL_LAPSES = {"access", "not-adopted", "outdated", "scope"}

rows = list(csv.DictReader(open(STATUS)))
cell = defaultdict(dict)               # cell[lgu][obl] = row
for r in rows:
    cell[r["lgu"]][r["obl_id"]] = r

def matrix():
    out = ["## Compliance matrix\n",
           "Legend: ✓ present · ◐ partial · · to-collect · ✗ absent · "
           "`!lapse` = lapse flag (see register).\n",
           "| Obligation | " + " | ".join(LGUS) + " |",
           "|---|" + "|".join(["---"]*len(LGUS)) + "|"]
    for oid, (label, cite) in OBLIG.items():
        cells = []
        for lgu in LGUS:
            r = cell.get(lgu, {}).get(oid)
            if not r:
                cells.append("·"); continue
            g = GLYPH.get(r["status"], "?")
            if r["lapse_type"] in REAL_LAPSES:
                g += f" !{r['lapse_type']}"
            cells.append(g)
        out.append(f"| **{oid}** {label} <br><sub>{cite}</sub> | "
                   + " | ".join(cells) + " |")
    return "\n".join(out)

def lapse_register():
    out = ["## Lapse register\n",
           "_Every logged lapse. `access` = exists but public can't view it — "
           "caps public-display obligations at partial._\n",
           "| LGU | Obl | Lapse | Note | Verified |",
           "|---|---|---|---|---|"]
    n = 0
    for r in rows:
        if r["lapse_type"] in REAL_LAPSES:
            note = (r["evidence"] or "").replace("|", "/")
            out.append(f"| {r['lgu']} | {r['obl_id']} | **{r['lapse_type']}** | "
                       f"{note} | {r['verified']} |")
            n += 1
    out.append(f"\n_{n} lapses logged._")
    return "\n".join(out)

def per_lgu():
    out = ["## Per-LGU detail\n"]
    for lgu in LGUS:
        out.append(f"### {lgu}\n")
        out.append("| Obl | Status | Lapse | Evidence | Source | Updated |")
        out.append("|---|---|---|---|---|---|")
        for oid, (label, _) in OBLIG.items():
            r = cell.get(lgu, {}).get(oid, {})
            st = GLYPH.get(r.get("status",""), "·") + " " + r.get("status","to-collect")
            out.append(f"| {oid} | {st} | {r.get('lapse_type','') or '—'} | "
                       f"{(r.get('evidence','') or '—').replace('|','/')} | "
                       f"{r.get('source_url','') or '—'} | {r.get('updated','')} |")
        out.append("")
    return "\n".join(out)

def progress():
    out = ["## Progress summary\n",
           "| LGU | present | partial | to-collect | absent | lapses |",
           "|---|---|---|---|---|---|"]
    for lgu in LGUS:
        c = defaultdict(int); laps = 0
        for oid in OBLIG:
            r = cell.get(lgu, {}).get(oid)
            if r:
                c[r["status"]] += 1
                if r["lapse_type"] in REAL_LAPSES:
                    laps += 1
        out.append(f"| {lgu} | {c['present']} | {c['partial']} | "
                   f"{c['to-collect']} | {c['absent']} | {laps} |")
    return "\n".join(out)

log = open(LOG).read().rstrip()
doc = "\n\n".join([
    "<!-- GENERATED by render_ledger.py — edit log.md / status.csv, not this file. -->",
    log, matrix(), progress(), lapse_register(), per_lgu(),
])
open(OUT, "w").write(doc + "\n")
print(f"Wrote {OUT}\n")
print(matrix()); print(); print(progress())
